#!/usr/bin/env python

console = bld.new_task_gen ('cc', 'staticlib')
console.find_sources_in_dirs ('.')
console.uselib = 'GSTREAMER'
console.packages = 'gstreamer-0.10'
console.vapi_dirs = '.'
console.target='galactica.console.static'
console.threading = True
console.install_path = None
