#!/usr/bin/env python

galactica = bld.new_task_gen ('cc', 'program')
galactica.find_sources_in_dirs ('.')
galactica.uselib='GLIB GSTREAMER'
galactica.packages = 'gstreamer-0.10'
galactica.target='galactica'
galactica.threading = True
